[2023-05-02 17:08:17,382] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.fact_nds manual__2023-05-02T17:07:23.457042+00:00 [queued]>
[2023-05-02 17:08:17,442] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.fact_nds manual__2023-05-02T17:07:23.457042+00:00 [queued]>
[2023-05-02 17:08:17,444] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-02 17:08:17,444] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-05-02 17:08:17,445] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-02 17:08:17,538] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): fact_nds> on 2023-05-02 17:07:23.457042+00:00
[2023-05-02 17:08:17,548] {standard_task_runner.py:52} INFO - Started process 2032 to run task
[2023-05-02 17:08:17,557] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'fact_nds', 'manual__2023-05-02T17:07:23.457042+00:00', '--job-id', '831', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmpjxl20k26', '--error-file', '/tmp/tmp9jgiujg3']
[2023-05-02 17:08:17,560] {standard_task_runner.py:80} INFO - Job 831: Subtask fact_nds
[2023-05-02 17:08:17,935] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.fact_nds manual__2023-05-02T17:07:23.457042+00:00 [running]> on host 295d97741f96
[2023-05-02 17:08:18,786] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=fact_nds
AIRFLOW_CTX_EXECUTION_DATE=2023-05-02T17:07:23.457042+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-02T17:07:23.457042+00:00
[2023-05-02 17:08:18,873] {base.py:68} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-05-02 17:08:19,181] {base.py:68} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-05-02 17:08:20,262] {python.py:173} INFO - Done. Returned value was: None
[2023-05-02 17:08:20,391] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=fact_nds, execution_date=20230502T170723, start_date=20230502T170817, end_date=20230502T170820
[2023-05-02 17:08:20,478] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-02 17:08:20,832] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
