[2023-05-04 05:15:21,289] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.fact_nds manual__2023-05-04T05:14:23.870311+00:00 [queued]>
[2023-05-04 05:15:21,350] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.fact_nds manual__2023-05-04T05:14:23.870311+00:00 [queued]>
[2023-05-04 05:15:21,351] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-04 05:15:21,352] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-05-04 05:15:21,353] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-04 05:15:21,442] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): fact_nds> on 2023-05-04 05:14:23.870311+00:00
[2023-05-04 05:15:21,451] {standard_task_runner.py:52} INFO - Started process 1205 to run task
[2023-05-04 05:15:21,468] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'fact_nds', 'manual__2023-05-04T05:14:23.870311+00:00', '--job-id', '968', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmpebi3uy4q', '--error-file', '/tmp/tmpem7znr69']
[2023-05-04 05:15:21,471] {standard_task_runner.py:80} INFO - Job 968: Subtask fact_nds
[2023-05-04 05:15:21,924] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.fact_nds manual__2023-05-04T05:14:23.870311+00:00 [running]> on host 295d97741f96
[2023-05-04 05:15:22,722] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=fact_nds
AIRFLOW_CTX_EXECUTION_DATE=2023-05-04T05:14:23.870311+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-04T05:14:23.870311+00:00
[2023-05-04 05:15:22,819] {base.py:68} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-05-04 05:15:23,161] {base.py:68} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-05-04 05:15:24,283] {python.py:173} INFO - Done. Returned value was: None
[2023-05-04 05:15:24,401] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=fact_nds, execution_date=20230504T051423, start_date=20230504T051521, end_date=20230504T051524
[2023-05-04 05:15:24,507] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-04 05:15:24,884] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
