[2023-05-03 18:36:07,394] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.clear_data_directory manual__2023-05-03T18:34:59.697678+00:00 [queued]>
[2023-05-03 18:36:07,473] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.clear_data_directory manual__2023-05-03T18:34:59.697678+00:00 [queued]>
[2023-05-03 18:36:07,475] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-03 18:36:07,477] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-05-03 18:36:07,478] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-03 18:36:07,577] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): clear_data_directory> on 2023-05-03 18:34:59.697678+00:00
[2023-05-03 18:36:07,591] {standard_task_runner.py:52} INFO - Started process 598 to run task
[2023-05-03 18:36:07,600] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'clear_data_directory', 'manual__2023-05-03T18:34:59.697678+00:00', '--job-id', '866', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmpxdpmu6vf', '--error-file', '/tmp/tmpte3elnvg']
[2023-05-03 18:36:07,603] {standard_task_runner.py:80} INFO - Job 866: Subtask clear_data_directory
[2023-05-03 18:36:08,000] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.clear_data_directory manual__2023-05-03T18:34:59.697678+00:00 [running]> on host 295d97741f96
[2023-05-03 18:36:08,615] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=clear_data_directory
AIRFLOW_CTX_EXECUTION_DATE=2023-05-03T18:34:59.697678+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-03T18:34:59.697678+00:00
[2023-05-03 18:36:08,623] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-05-03 18:36:08,627] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'rm -rf ${pwd}data/* | echo "приехали"']
[2023-05-03 18:36:08,649] {subprocess.py:85} INFO - Output:
[2023-05-03 18:36:08,706] {subprocess.py:92} INFO - приехали
[2023-05-03 18:36:08,750] {subprocess.py:96} INFO - Command exited with return code 0
[2023-05-03 18:36:09,002] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=clear_data_directory, execution_date=20230503T183459, start_date=20230503T183607, end_date=20230503T183609
[2023-05-03 18:36:09,108] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-03 18:36:09,384] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
