[2023-05-05 05:32:56,296] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.sensor_s3_obj manual__2023-05-05T05:32:51.253337+00:00 [queued]>
[2023-05-05 05:32:56,356] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.sensor_s3_obj manual__2023-05-05T05:32:51.253337+00:00 [queued]>
[2023-05-05 05:32:56,358] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-05 05:32:56,359] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-05-05 05:32:56,360] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-05 05:32:56,453] {taskinstance.py:1377} INFO - Executing <Task(S3KeySensor): sensor_s3_obj> on 2023-05-05 05:32:51.253337+00:00
[2023-05-05 05:32:56,461] {standard_task_runner.py:52} INFO - Started process 598 to run task
[2023-05-05 05:32:56,469] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'sensor_s3_obj', 'manual__2023-05-05T05:32:51.253337+00:00', '--job-id', '1025', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmp48vbychf', '--error-file', '/tmp/tmpnuwug1df']
[2023-05-05 05:32:56,471] {standard_task_runner.py:80} INFO - Job 1025: Subtask sensor_s3_obj
[2023-05-05 05:32:56,847] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.sensor_s3_obj manual__2023-05-05T05:32:51.253337+00:00 [running]> on host 295d97741f96
[2023-05-05 05:32:57,419] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=sensor_s3_obj
AIRFLOW_CTX_EXECUTION_DATE=2023-05-05T05:32:51.253337+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-05T05:32:51.253337+00:00
[2023-05-05 05:32:57,423] {s3.py:104} INFO - Poking for key : s3://raw/supermarket_sales.csv
[2023-05-05 05:32:57,501] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2023-05-05 05:32:57,505] {base_aws.py:206} INFO - Credentials retrieved from login
[2023-05-05 05:33:02,848] {s3.py:104} INFO - Poking for key : s3://raw/supermarket_sales.csv
[2023-05-05 05:33:07,872] {s3.py:104} INFO - Poking for key : s3://raw/supermarket_sales.csv
[2023-05-05 05:33:08,078] {base.py:301} INFO - Success criteria met. Exiting.
[2023-05-05 05:33:08,198] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=sensor_s3_obj, execution_date=20230505T053251, start_date=20230505T053256, end_date=20230505T053308
[2023-05-05 05:33:08,331] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-05 05:33:08,727] {local_task_job.py:273} INFO - 2 downstream tasks scheduled from follow-on schedule check
