[2023-08-17 17:41:28,738] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl.fact_nds manual__2023-08-17T17:41:19.800552+00:00 [queued]>
[2023-08-17 17:41:28,745] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl.fact_nds manual__2023-08-17T17:41:19.800552+00:00 [queued]>
[2023-08-17 17:41:28,745] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-17 17:41:28,745] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-08-17 17:41:28,746] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-17 17:41:28,754] {taskinstance.py:1397} INFO - Executing <Task(_PythonDecoratedOperator): fact_nds> on 2023-08-17 17:41:19.800552+00:00
[2023-08-17 17:41:28,758] {standard_task_runner.py:52} INFO - Started process 560 to run task
[2023-08-17 17:41:28,762] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'fact_nds', 'manual__2023-08-17T17:41:19.800552+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmpmnocg7hg', '--error-file', '/tmp/tmpn6phdqlg']
[2023-08-17 17:41:28,763] {standard_task_runner.py:80} INFO - Job 78: Subtask fact_nds
[2023-08-17 17:41:28,822] {task_command.py:371} INFO - Running <TaskInstance: dag_etl.fact_nds manual__2023-08-17T17:41:19.800552+00:00 [running]> on host 1ea22a5e1d7f
[2023-08-17 17:41:28,895] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=fact_nds
AIRFLOW_CTX_EXECUTION_DATE=2023-08-17T17:41:19.800552+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-17T17:41:19.800552+00:00
[2023-08-17 17:41:28,906] {base.py:68} INFO - Using connection ID '***_conn' for task execution.
[2023-08-17 17:41:28,946] {base.py:68} INFO - Using connection ID '***_conn' for task execution.
[2023-08-17 17:41:29,080] {python.py:173} INFO - Done. Returned value was: None
[2023-08-17 17:41:29,213] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=fact_nds, execution_date=20230817T174119, start_date=20230817T174128, end_date=20230817T174129
[2023-08-17 17:41:29,260] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-17 17:41:29,300] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
