[2023-05-04 05:11:35,105] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.extract_from_s3 manual__2023-05-04T05:10:16.045945+00:00 [queued]>
[2023-05-04 05:11:36,203] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.extract_from_s3 manual__2023-05-04T05:10:16.045945+00:00 [queued]>
[2023-05-04 05:11:36,228] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-04 05:11:36,239] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-05-04 05:11:36,264] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-04 05:11:37,350] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): extract_from_s3> on 2023-05-04 05:10:16.045945+00:00
[2023-05-04 05:11:37,422] {standard_task_runner.py:52} INFO - Started process 801 to run task
[2023-05-04 05:11:37,575] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'extract_from_s3', 'manual__2023-05-04T05:10:16.045945+00:00', '--job-id', '938', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmpkew0a5l7', '--error-file', '/tmp/tmpio97ume1']
[2023-05-04 05:11:37,629] {standard_task_runner.py:80} INFO - Job 938: Subtask extract_from_s3
[2023-05-04 05:11:40,578] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.extract_from_s3 manual__2023-05-04T05:10:16.045945+00:00 [running]> on host 295d97741f96
[2023-05-04 05:11:48,292] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=extract_from_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-05-04T05:10:16.045945+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-04T05:10:16.045945+00:00
[2023-05-04 05:11:48,319] {s3.py:861} INFO - Downloading source S3 file from Bucket raw with path supermarket_sales.csv
[2023-05-04 05:11:49,713] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2023-05-04 05:11:49,772] {base_aws.py:206} INFO - Credentials retrieved from login
[2023-05-04 05:11:59,664] {python.py:173} INFO - Done. Returned value was: /opt/***/data/***_tmp_71qi202i
[2023-05-04 05:12:01,335] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=extract_from_s3, execution_date=20230504T051016, start_date=20230504T051135, end_date=20230504T051201
[2023-05-04 05:12:02,057] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-04 05:12:03,965] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
