[2023-05-04 20:04:44,934] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.extract_from_s3 manual__2023-05-04T20:04:31.370742+00:00 [queued]>
[2023-05-04 20:04:45,049] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.extract_from_s3 manual__2023-05-04T20:04:31.370742+00:00 [queued]>
[2023-05-04 20:04:45,051] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-04 20:04:45,052] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-05-04 20:04:45,053] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-04 20:04:45,182] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): extract_from_s3> on 2023-05-04 20:04:31.370742+00:00
[2023-05-04 20:04:45,200] {standard_task_runner.py:52} INFO - Started process 756 to run task
[2023-05-04 20:04:45,234] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'extract_from_s3', 'manual__2023-05-04T20:04:31.370742+00:00', '--job-id', '990', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmpwxiy_tdv', '--error-file', '/tmp/tmphl6twlpa']
[2023-05-04 20:04:45,238] {standard_task_runner.py:80} INFO - Job 990: Subtask extract_from_s3
[2023-05-04 20:04:45,807] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.extract_from_s3 manual__2023-05-04T20:04:31.370742+00:00 [running]> on host 295d97741f96
[2023-05-04 20:04:46,619] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=extract_from_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-05-04T20:04:31.370742+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-04T20:04:31.370742+00:00
[2023-05-04 20:04:46,629] {s3.py:861} INFO - Downloading source S3 file from Bucket raw with path supermarket_sales.csv
[2023-05-04 20:04:46,772] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2023-05-04 20:04:46,783] {base_aws.py:206} INFO - Credentials retrieved from login
[2023-05-04 20:04:47,878] {python.py:173} INFO - Done. Returned value was: /opt/***/data/***_tmp_n5ua9fn9
[2023-05-04 20:04:48,261] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=extract_from_s3, execution_date=20230504T200431, start_date=20230504T200444, end_date=20230504T200448
[2023-05-04 20:04:48,383] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-04 20:04:48,824] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
