[2023-05-04 20:03:47,968] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.fact_nds manual__2023-05-04T20:02:47.981671+00:00 [queued]>
[2023-05-04 20:03:48,028] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.fact_nds manual__2023-05-04T20:02:47.981671+00:00 [queued]>
[2023-05-04 20:03:48,030] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-04 20:03:48,030] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-05-04 20:03:48,031] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-04 20:03:48,123] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): fact_nds> on 2023-05-04 20:02:47.981671+00:00
[2023-05-04 20:03:48,132] {standard_task_runner.py:52} INFO - Started process 667 to run task
[2023-05-04 20:03:48,141] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'fact_nds', 'manual__2023-05-04T20:02:47.981671+00:00', '--job-id', '985', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmpnuppywph', '--error-file', '/tmp/tmpd682ncot']
[2023-05-04 20:03:48,144] {standard_task_runner.py:80} INFO - Job 985: Subtask fact_nds
[2023-05-04 20:03:48,511] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.fact_nds manual__2023-05-04T20:02:47.981671+00:00 [running]> on host 295d97741f96
[2023-05-04 20:03:49,177] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=fact_nds
AIRFLOW_CTX_EXECUTION_DATE=2023-05-04T20:02:47.981671+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-04T20:02:47.981671+00:00
[2023-05-04 20:03:49,267] {base.py:68} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-05-04 20:03:49,561] {base.py:68} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-05-04 20:03:50,571] {python.py:173} INFO - Done. Returned value was: None
[2023-05-04 20:03:50,683] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=fact_nds, execution_date=20230504T200247, start_date=20230504T200347, end_date=20230504T200350
[2023-05-04 20:03:50,783] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-04 20:03:51,095] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
