[2023-04-30 09:01:02,915] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.fact_stage manual__2023-04-30T08:59:26.372167+00:00 [queued]>
[2023-04-30 09:01:02,989] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.fact_stage manual__2023-04-30T08:59:26.372167+00:00 [queued]>
[2023-04-30 09:01:02,991] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 09:01:02,992] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-04-30 09:01:02,993] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 09:01:03,094] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): fact_stage> on 2023-04-30 08:59:26.372167+00:00
[2023-04-30 09:01:03,104] {standard_task_runner.py:52} INFO - Started process 562 to run task
[2023-04-30 09:01:03,119] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'fact_stage', 'manual__2023-04-30T08:59:26.372167+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmp2ywpzrse', '--error-file', '/tmp/tmp8mb3jocv']
[2023-04-30 09:01:03,122] {standard_task_runner.py:80} INFO - Job 182: Subtask fact_stage
[2023-04-30 09:01:03,522] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.fact_stage manual__2023-04-30T08:59:26.372167+00:00 [running]> on host 295d97741f96
[2023-04-30 09:01:04,290] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=fact_stage
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T08:59:26.372167+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-30T08:59:26.372167+00:00
[2023-04-30 09:01:04,375] {base.py:68} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-04-30 09:01:04,735] {base.py:68} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-04-30 09:01:05,794] {python.py:173} INFO - Done. Returned value was: None
[2023-04-30 09:01:05,917] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=fact_stage, execution_date=20230430T085926, start_date=20230430T090102, end_date=20230430T090105
[2023-04-30 09:01:06,049] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-30 09:01:06,527] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
